### ISSUE TITLE
Add Redis to web server

### ISSUE THREAD

**Issue by paulbeattie** [paulbeattie/aws-ansible-rails#6]
Add Redis to web task group to setup Redis.

There are currently three options for this, the Redis recommended way which involves manually downloading, building and setting up Redis or using the package manager for the system which can result in an old version of Redis being installed and never changing. The third option is that we use a PPA such as https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server?field.series_filter=trusty. 

cc @ryanmacg

**Comment by RyanMacG** [comment]
Shall we go with the recommended solution?

**Comment by paulbeattie** [comment]
Included in https://github.com/paulbeattie/aws-ansible-rails/commit/ab639ea1c133a2522c5aeb9510400c30f28a6471. https://github.com/paulbeattie/aws-ansible-rails/tree/redis still present for now in case any further changes are required.
